---
version: 0.2
env:
  variables:
    BACKUP_DATE_PARAM: "/$ENV_TYPE/nextcloud/db/restore/timestamp"
phases:
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}
      - make ${ACTION_TYPE}
